title: failchat
description: Простой и бесплатный мультичат для стримеров
theme: jekyll-theme-cayman

github:
  is_project_page: false

failchat:
  setup: "https://github.com/onoderis/failchat/wiki/%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%87%D0%B0%D1%82%D0%B0"
  discord: "https://discord.gg/4Qs3Y8h"

google_analytics: UA-73079300-4
